### ISSUE TITLE
bot en twitter

### ISSUE THREAD

**Issue by catdevnull** [catdevnull/milei-twitter#20]

**Comment by catdevnull** [comment]
alguien lo armo!

twitter.com/qhacemilei

https://github.com/qhacemilei/qhacemileiBot

**Comment by catdevnull** [comment]
* [ ] armar API para que consuma el bot

**Comment by qhacemilei** [comment]
Está todo listo, faltaría un api para consumir mejor la información. 

Algunas ideas: 

1.  Subir un post todos los domingos con el recuento de la semana.
2.  Lo mismo pero mensual.

**Comment by catdevnull** [comment]
desapareció qhacemilei, no sabemos que onda. por ahora se reabre

**Comment by catdevnull** [comment]
Empezado en https://twitter.com/LikesMilei8865, continuo en #56
