### ISSUE TITLE
Ultima vez actualizado - hora actual

### ISSUE THREAD

**Issue by zuruckinsmeer** [catdevnull/milei-twitter#28]
El horario que se indica en "última vez actualizado" debería ser el último intento de recuperación de likes nuevos (o la hora actual, que deberían ser esencialmente coincidentes). De esa forma se puede observar si hay un silencio en progreso cuando la vista corresponde a las últimas 24hs o el día actual. 
Eso tendría que estar reflejado también en el histograma, mostrando hasta la hora actual (con horas "vacías" si correspondiera).

**Comment by catdevnull** [comment]
ya estoy en esto!

**Comment by catdevnull** [comment]
ahora estoy empezando a guardar si el scrap llegó a ver tuits, que basicamente es una forma de enterarse si scrappear falló o no. https://github.com/catdevnull/milei-twitter/commit/ac2450ead954c1f64e9166478e9b41dd42363c92

entonces va a ser solo buscar el último scrap con tuits vistos > 0
